### ISSUE TITLE
reports

### ISSUE THREAD

**Issue by firedom** [kattgu7/Anti-996-License#1]
最近看到了一个关于996ICU许可证的讨论[1]，已经有人已经想到在国家相关法律的基础上派生出一份用于开源项目的许可证了（good idea）。

然而这个许可证从名字来看似乎存在着一个“contradictio in adjecto”式的矛盾，即可以认为某个使用包含“禁止996许可证”的项目的人“只要遵守许可证的条款就可以合法的996”。为了试图消除这个看起来很神奇的矛盾，可以尝试从这些方面进行修改：

1. 为许可证找一个更合适的名字；
2. 996问题目前主要流行于中国，因此必须有一个中文版许可证以便让更多的人了解并参与进来；
5. 要求使用者只有同意许可证条款的情况下才能使用这个项目；
4. 996ICU许可证是面向雇员的许可证，非雇员开发者是否有必要遵守这个许可证；
5. 是否有必要让该许可证具有传染性；
6. 是否有必要让该许可证的优先级高于其它一切许可证；（类似宪法）
7. 雇员及团体的关系；
8. （*重要*）原“996ICU许可证”与《中华人民共和国劳动法》第四章第三十九条相冲突，会导致遵守许可证的同时依然996。因此有必要制定一份独立的、不在任何国家相关劳动法律基础上添加附加规定的许可证；
9. 该许可证主要保护能为实体创造价值但是无法得到合理回报的员工，是否还应该保护在实体内混吃等死不想被裁员反而起来搞事的员工；

10. 大公司为了降低法律风险通常会自己开发需要的项目，一般不会首先考虑使用开源项目；（不但能降低法律风险还能拿国家投资）

11.人的生理极限无法超越机器（even machine learning），当工作效率无法满足要求时裁员不可避免。先想想你要的到底是什么。

试图写一个非常不完善的许可证：

<p align="center">合法劳动 a.k.a Abandon996 许可证</p>
<p align="center">Version 0.1.1, March 2019</p>

使用本项目者必须严格遵守以下条款：

第一条 保护身份为雇员的开发者的合法劳动时间是社区以及全社会的共同责任。一切组织和个人对损害雇员合法劳动时间的行为有监督和举报的义务。

第二条 使用本项目的雇员和必须保证自己的工作满足：[3]
	3.1 一天工作时间为 8 小时，平均每周工时不超过 40 小时；
	3.2 加班上限为一天 3 小时及一个月 36 小时，逾时工作薪金不低于平日工资的 150%。而一周最高工时则为 48 小时。平均每月计薪天数为 21.75 天。

第三条 使用本项目的组织必须保证自身的人力资源工作时间满足本许可证第二条之规定；

第四条 当一个项目中没有包含此许可证，但是其子项目包含该许可证时，违反第二条规定的雇员不可以使用该子项目。

事实上就目前来看制定996许可证就是一场自嗨[2]，但是996问题就像“八小时工作制”一样是不可能在一夜之间解决。只有通过各种形式的宣传让尽量多的人参与进来，那这个问题才会在未来某一天以所有人都想象不到的方式解决被彻底解决。

[1] https://github.com/996icu/996.ICU/pull/15642
[2] https://www.v2ex.com/t/550243
[3] https://996.icu/#/zh_CN

**Comment by kattgu7** [comment]
Response to your comments:

1. I agree with renaming the license. This is just a temporary name.

2. I can translate that into Chinese. I'm working on it.

3. I'll think about how to add this.

4. I think it should apply to independent contractors. In US independent contractors are also protected.

5. I'm thinking about hold the contamination clause at this moment because this will prevent people from adopting it.  We can add it to the license in the future version.

6. No. No license should trump the others.

7. I don't quite get this point. The relationship should not be something that this license is able to define.

8. I know this clause. But the draft license is not in conflict with Article 4, Clause 39 of Labor Law of China. The clause does offer exemptions for companies, but the premise is that it should comply with the labor law of China (that's the legal explanation as I see from Chinese sources, the labor should be construed as a whole). We can not create something above law, cuz it will be enforceable (basically the court can decide any time the license is void, and the companies can refuse to adopt that because it requires something beyond what law requires. No one wants to comply with stricter standards). We can not expect radical change to happen in one night, and compliance with the law is the things we can do right now. 

9. I believe that's an ethical or moral question that cannot be addressed here.

10&11. I agree with what you said

Finally, I want to say that I can draft a license like Apache, GPL or so, but it requires time, and it needs expert specialization in labor law (I'm more on international treaty and human rights side). I think the key point for the license is, we should not rewrite labor law (not practical and enforceable), and licenses such as MIT only grant power protected by copyright or patent law. In addition, I think we should allow anyone who wants to use the draft to adopt it right now because if we don't do that, people will forget this in weeks. 

BTW, my background is in environmental science and law (and a little bit of information science), and I have to admit I'm not familiar with topics that are too technical (but I do participate in some legislative and standard-setting processes before so I know how they work). I'm happy to explain any doubt any of you have on the draft license and I welcome any comment and thought.

**Comment by Tedko** [comment]
重点解释一下，为什么不专门把时间写在许可证里：

>We can not create something above law, cuz it will be enforceable (basically the court can decide any time the license is void, and the companies can refuse to adopt that because it requires something beyond what law requires. No one wants to comply with stricter standards). We can not expect radical change to happen in one night, and compliance with the law is the things we can do right now.

**Comment by ff4415** [comment]
> 重点解释一下，为什么不专门把时间写在许可证里：
> 
> > We can not create something above law, cuz it will be enforceable (basically the court can decide any time the license is void, and the companies can refuse to adopt that because it requires something beyond what law requires. No one wants to comply with stricter standards). We can not expect radical change to happen in one night, and compliance with the law is the things we can do right now.

引用的内容好像和你的问题无关。

**Comment by ff4415** [comment]
不可能面面俱到，短时间内能有一个方向的突破就很不错了。 精力要集中。 focus!  

我觉得在GPL的基础上往前推进一步就可以了。  因为只有这个license 才是最有力量的。

**Comment by Tedko** [comment]
@ff4415
可以看下wiki，有写一下extra解释
